// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/channel_role/channel_role.proto

package channel_role

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChannelRoleService_Create_FullMethodName           = "/v1.channel_role.ChannelRoleService/Create"
	ChannelRoleService_ListChannelRoles_FullMethodName = "/v1.channel_role.ChannelRoleService/ListChannelRoles"
	ChannelRoleService_Delete_FullMethodName           = "/v1.channel_role.ChannelRoleService/Delete"
)

// ChannelRoleServiceClient is the client API for ChannelRoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChannelRoleServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	ListChannelRoles(ctx context.Context, in *ListChannelRolesRequest, opts ...grpc.CallOption) (*ListChannelRolesResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type channelRoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelRoleServiceClient(cc grpc.ClientConnInterface) ChannelRoleServiceClient {
	return &channelRoleServiceClient{cc}
}

func (c *channelRoleServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, ChannelRoleService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelRoleServiceClient) ListChannelRoles(ctx context.Context, in *ListChannelRolesRequest, opts ...grpc.CallOption) (*ListChannelRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChannelRolesResponse)
	err := c.cc.Invoke(ctx, ChannelRoleService_ListChannelRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelRoleServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ChannelRoleService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelRoleServiceServer is the server API for ChannelRoleService service.
// All implementations must embed UnimplementedChannelRoleServiceServer
// for forward compatibility.
type ChannelRoleServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	ListChannelRoles(context.Context, *ListChannelRolesRequest) (*ListChannelRolesResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedChannelRoleServiceServer()
}

// UnimplementedChannelRoleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelRoleServiceServer struct{}

func (UnimplementedChannelRoleServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedChannelRoleServiceServer) ListChannelRoles(context.Context, *ListChannelRolesRequest) (*ListChannelRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChannelRoles not implemented")
}
func (UnimplementedChannelRoleServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedChannelRoleServiceServer) mustEmbedUnimplementedChannelRoleServiceServer() {}
func (UnimplementedChannelRoleServiceServer) testEmbeddedByValue()                            {}

// UnsafeChannelRoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelRoleServiceServer will
// result in compilation errors.
type UnsafeChannelRoleServiceServer interface {
	mustEmbedUnimplementedChannelRoleServiceServer()
}

func RegisterChannelRoleServiceServer(s grpc.ServiceRegistrar, srv ChannelRoleServiceServer) {
	// If the following call pancis, it indicates UnimplementedChannelRoleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChannelRoleService_ServiceDesc, srv)
}

func _ChannelRoleService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelRoleServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelRoleService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelRoleServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelRoleService_ListChannelRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelRoleServiceServer).ListChannelRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelRoleService_ListChannelRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelRoleServiceServer).ListChannelRoles(ctx, req.(*ListChannelRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelRoleService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelRoleServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelRoleService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelRoleServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChannelRoleService_ServiceDesc is the grpc.ServiceDesc for ChannelRoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelRoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.channel_role.ChannelRoleService",
	HandlerType: (*ChannelRoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ChannelRoleService_Create_Handler,
		},
		{
			MethodName: "ListChannelRoles",
			Handler:    _ChannelRoleService_ListChannelRoles_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ChannelRoleService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/channel_role/channel_role.proto",
}
